services:
  db:
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    network_mode: "host"
    volumes:
      - ./db:/data/db
    environment:
      POSTGRES_DB: password_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ss1488ppkk